name: Create Branch from Issue

on:
    issue_comment:
        types: [created]

jobs:
    create_branch:
        
        if: github.event.comment.body == '/branch'
        runs-on: ubuntu-latest

        permissions:
            contents: write
            issues: read

        steps:
        - 
            name: Check out repository
            uses: actions/checkout@v3

        -
            name: Generate branch name
            id: generate_branch_name
            env: 
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: |
                ISSUE_NUMBER=${{ github.event.issue.number }}
                ISSUE_TITLE=${{ github.event.issue.title }}

                if gh issue view $ISSUE_NUMBER --json labels --jq '.labels[].name' | grep -q 'bug'; then
                  BRANCH_TYPE="bug"
                else
                  BRANCH_TYPE="feature"
                fi

                BRANCH_NAME="${BRANCH_TYPE}/issue-${ISSUE_NUMBER}"
                echo "target_branch=$BRANCH_NAME" >> $GITHUB_OUTPUT

        -
            name: Create branch
            run: |
                git config user.name "github-actions[bot]"
                git config user.email "github-actions[bot]@users.noreply.github.com"

                BASE_BRANCH = "main"
                TARGET_BRANCH = ${{ steps.generate_branch_name.outputs.target_branch }}

                git fetch origin $BASE_BRANCH
                git checkout -b $TARGET_BRANCH origin/$BASE_BRANCH
                git push origin $TARGET_BRANCH

        -
            name: Comment on issue
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: |
                ISSUE_NUMBER=${{ github.event.issue.number }}
                BRANCH_NAME=${{ steps.generate_branch_name.outputs.target_branch }}

                gh issue comment $ISSUE_NUMBER --body "Branch created: [${BRANCH_NAME}](
