name: Test Code upon Pull Request

on:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            - edited
            - ready_for_review

jobs: 
    test_pull_request:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            pull-requests: write

        steps:

            -
                name: Check out repository
                uses: actions/checkout@v3

            -
                name: Run tests
                id: run_tests
                run: ./test.bash
                continue-on-error: true

            -
                name: Comment on pull request
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: |
                    PR_NUMBER=${{ github.event.pull_request.number }}
                    
                    if [ "${{ steps.run_tests.outcome }}" == "failure" ]; then
                        LOG_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                        COMMENT="Tests failed. Please check the [logs](${LOG_URL}) for details."
                    else
                        COMMENT="All tests passed! Ready to merge."
                    fi
